# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e74c31fcd6afbf9a73e9f23554429b7"
application_url = "https://blow-monitor-against-struggle.trycloudflare.com"
embedded = true
name = "fantasticfy-test1"
handle = "fantasticfy-test1-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_shipping,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://blow-monitor-against-struggle.trycloudflare.com/auth/callback",
  "https://blow-monitor-against-struggle.trycloudflare.com/auth/shopify/callback",
  "https://blow-monitor-against-struggle.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
